feat: support trigger
artusjs/core pull request #10
Opened 2022-03-18 01:53 UTC by hyj1991

2022-03-18 04:30 UTC, noahziheng requested changes

2022-03-18 04:30 UTC, noahziheng commented on src/trigger.ts
> +  id: ARTUS_TRIGGER_ID,
这个地方不需要用常量吧，可以直接用类作为索引 cc @JerrysShan

2022-03-18 04:30 UTC, noahziheng commented on src/trigger.ts
> +  #pipeline = new Pipeline();
要不直接统一 TS 的 private？感觉好理解一些

2022-03-18 04:34 UTC, noahziheng commented on package.json
> +    "@artus/injection": "^0.0.2",
这版本号是该统一一下了（doge

2022-03-18 04:35 UTC, hyj1991 commented on src/trigger.ts
> +  id: ARTUS_TRIGGER_ID,
需要从别的地方覆盖（例如 HttpTrigger），不用常量看起来不是很好操作

2022-03-18 04:35 UTC, hyj1991 commented on src/trigger.ts
> +  #pipeline = new Pipeline();
TS 的 private 只是静态校验，实际还是可以在外部访问到的，class private fied 可以完全避免从外部的访问（打包后的 js）

2022-03-18 04:37 UTC, noahziheng commented on src/application.ts
> +  // @ts-ignore
此处的 ignore 是初始值？感觉这会成个问题，要不考虑 Inject 放在 constructor 里算了 @JerrysShan

2022-03-18 04:38 UTC, noahziheng commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
都 async 了，要不加个 await 以后 use 支持 Promise？

2022-03-18 04:42 UTC, hyj1991 commented on src/application.ts
> +  // @ts-ignore
目前 @Inject 不加 ignore 这里会报错，这个需要 @JerrysShan 看下如何规避掉

2022-03-18 04:43 UTC, hyj1991 commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
其实我基本上给所有的函数都预留了 async，目前也只是异步传染下的一种防守策略

2022-03-18 04:55 UTC, noahziheng commented on src/trigger.ts
> +  id: ARTUS_TRIGGER_ID,
get 到了，那确实要用常量

2022-03-18 04:57 UTC, noahziheng commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
但加了 await 才能彻底防住哇，现在这个状态不就成了只防一半

2022-03-18 04:59 UTC, noahziheng commented on src/trigger.ts
> +  #pipeline = new Pipeline();
其实统一就行，我那边用 private 的原因是从可读性上和 public protected 上并列好看一些

是否有必要从运行时也阻断访问我觉得要再考虑吧，意义不是很大的样子？

2022-03-18 05:03 UTC, noahziheng commented on src/application.ts
> +  // @ts-ignore
Issue Opened https://github.com/artusjs/injection/issues/4

暂时先 ignore 问题不大

2022-03-18 05:58 UTC, hyj1991 commented on src/trigger.ts
> +  #pipeline = new Pipeline();
可以防止黑魔法

2022-03-18 06:00 UTC, hyj1991 commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
防不住的意思是？这里虽然没有 await，但是并不影响整个 async 函数返回 `Promise<void>`

2022-03-18 06:15 UTC, hyj1991 commented on package.json
> +    "egg-ci": "^1.19.0",
// TODO: `egg-ci` 自动生成 ci 配置，可以考虑后面替换为 `@artus/ci` 来进行统一维护

2022-03-18 06:17 UTC, hyj1991 commented on package.json
> +    "@artus/injection": "^0.0.2",
`0.x` 的版本其实相对比较随意，如果 `injection` 基本功能已经实现完毕可以直接发一个 minor 版本，看着会更加舒服一些，重要的是按照计划四月底一起发 1.x 版本出来

2022-03-18 07:03 UTC, noahziheng commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
就 use 内仍然不能有异步行为，否则时序不就乱了

2022-03-18 07:04 UTC, noahziheng commented on package.json
> +    "@artus/injection": "^0.0.2",
嗯，影响不大，下个版本和你 pipeline 一样发 minor 就是了  cc @JerrysShan

2022-03-18 07:06 UTC, noahziheng commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
个人看法的话，没有特殊需求的话，async-await 还是要成对使用相对清晰一些？

2022-03-18 07:31 UTC, hyj1991 commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
> 就 use 内仍然不能有异步行为，否则时序不就乱了

这就是 async 防守的意义，比如现在 use 是同步的，以后改成异步，那么这里就可以直接写

```ts
await pipeline.use(middleware)
```

而无需影响到已经使用到 trigger 逻辑封装的上层框架。

至于你说的成对使用，从规范中来看的话，`await` 并没有和 `asyncMehod` 绑定，其实严格说它需要的是 `asyncContext` 来作为其 [running execution context](https://tc39.es/ecma262/#running-execution-context)，这里的一个例子就是 [top-level-await](https://github.com/tc39/proposal-top-level-await) 这个特性

2022-03-18 07:41 UTC, hyj1991 commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
不过我思考了一下，为了避免更多争议，最新的 commit 中我暂时将 `async` 删除了，还原为一个普通函数。

看起来这里的防守可能并没有必要，考虑到 egg/koa 生态跑了这么多年了，use 这个动作可能不存在会有异步的场景。

2022-03-18 07:56 UTC, noahziheng commented on src/trigger.ts
> +    this.#pipeline.use(middleware);
如飞书沟通，use 方法希望设计足够纯粹，不涉及异步化可能，此处的 async 防守目的是后续可能在 use 前后增加 async hook

2022-03-18 08:05 UTC, XadillaX commented on src/trigger.ts
> +  #pipeline = new Pipeline();
我个人偏向于投 `#` 一票。虽然这东西丑，但至少能保证跟 ECMAScript 的一致性。但我也乐意少数服从多数。

2022-03-18 08:09 UTC, JerrysShan commented on src/trigger.ts
> +  #pipeline = new Pipeline();
如果用TS 开发的话，建议使用private 吧

2022-03-18 08:49 UTC, hyj1991 commented on src/trigger.ts
> +  #pipeline = new Pipeline();
根据群里的投票，修改为 `private`

2022-03-18 08:51 UTC, atian25 commented on package.json
> +      "github": "linux, windows, macos"
这个不需要配置吧，不是默认 3 系统么？

2022-03-18 08:56 UTC, hyj1991 commented on package.json
> +      "github": "linux, windows, macos"
我先去掉这些默认的配置。

其实 egg-ci 现在是一个临时的方案（对应的 ci generate 配置也是一样），后面看看挪到 `@artus/ci` 做统一的维护

2022-03-18 09:01 UTC, noahziheng approved these changes

2022-03-18 09:01 UTC, noahziheng commented on package.json
> +    "egg-ci": "^1.19.0",
cc @BeAce

2022-03-18 09:02 UTC, merged

2022-03-20 03:53 UTC, fengmk2 commented on src/trigger.ts
> +import { ARTUS_TRIGGER_ID } from "./constraints";
我看 swc 项目的字符串全部使用 ` 来代替双引号或者单引号，解决了字符串的纠结，哈哈，后续我们可以看看。

2022-03-20 03:57 UTC, fengmk2 commented on test/fixtures/trigger-http/app.ts
> +        await app.trigger.startPipeline();
好精妙，对比 2010 年第一次看到 http server 的这个 req res 写法，我们的代码抽象能力已经不可同日而语。

2022-03-20 03:59 UTC, fengmk2 commented on src/trigger.ts
> +  constructor(){
这里的空间 eslint 配置没有检测出来。

2022-03-20 04:05 UTC, fengmk2 commented on test/trigger.test.ts
> +  describe('trigger with http', () => {
加一个定时任务的 trigger 示例？后续开发者应该可以从这个单测里面找到最佳的参考代码。

2022-03-20 04:06 UTC, fengmk2 commented on test/fixtures/trigger-http/httpTrigger.ts
> +export class HttpTrigger extends Trigger {
@popomore 看看是否你能够想象的 trigger 模型？

2022-03-20 05:35 UTC, hyj1991 commented on src/trigger.ts
> +  constructor(){
lint 规则其实还没加，lint 和 tsconfig 都还没统一，现在着力于先把 core 对上层提供的这些基础能力做出来

2022-03-20 05:39 UTC, hyj1991 commented on test/trigger.test.ts
> +  describe('trigger with http', () => {
是的， https://github.com/artusjs/core/pull/12 这个 pr 在 review，涉及到上周又讨论的 application lifestyle hook IoC 的提供形式，然后补充更多协议（和无协议）模型下的 trigger 示例