refactor: 支持 Plugin.package 字段在扫描阶段的预处理
artusjs/core pull request #110
Opened 2022-06-15 12:34 UTC by noahziheng

- Plugin 抽象 getPath 能力、增加 path/package 互斥判断
- Config 相关 Loader 重构，支持对 PluginConfig 进行预处理
- Scanner 局部逻辑重构
   - 重构 getAllConfig 兼容上述插件处理逻辑
   - 修正多环境条件下的配置数据隔离 BUG
   - 从 Manifest 中移除 PluginConfig，防止运行时对其的重新合并诱发两阶段配置状态不一致
 - 增加相关单元测试用例

resolve #109

2022-06-24 11:37 UTC, hyj1991 commented on src/scanner/scan.ts
> +    this.tmpConfigStore = new Map();
这个为啥不喝 itemMap 一样直接放到属性定义里初始化？

```ts
private tmpConfigStore: Map<string, ConfigObject[]> = new Map();
```

2022-06-24 11:39 UTC, hyj1991 commented on src/scanner/scan.ts
> +  private itemMap: Map<string, ManifestItem[]> = new Map();
`itemMap` 的初始化在构造函数里，这里属性定义时直接初始化是否有必要？

2022-06-24 11:43 UTC, hyj1991 commented on src/scanner/scan.ts
> +    const root = path.resolve(baseDir, configDir);
`config` 绝对路径定义为 `root` 有点奇怪

2022-06-24 11:48 UTC, hyj1991 commented on src/scanner/scan.ts
> +      }
既然都加了这个判断，为啥不直接强制使用 `config loader` 来加载 config 目录下的配置？

2022-06-24 11:49 UTC, hyj1991 commented on src/scanner/scan.ts
> +      }
最后读取 `plugin` 字段就行了，`config loader` 会自动根据 `filename.env.ext` 切割出来的 `filename` 作为 key 统一处理所有的 config，我觉得这样这里的处理逻辑反而清晰一些

2022-06-24 11:51 UTC, hyj1991 commented on src/scanner/scan.ts
> +      configList = configList.concat(this.tmpConfigStore.get(env) ?? []);
都判断 `this.tmpConfigStore.has(env)` 了，下面的 `?? []` 是多余的。

2022-06-24 11:54 UTC, hyj1991 commented on src/scanner/scan.ts
> +    });
这个可以简化下 `items.filter(item=> item.loader !== 'plugin-config')`，另外有点硬编码的意思，是不是可以将这种仅在 Scan 期间需要但是启动期间无需使用的配置放到 Scanner 的配置属性中

以便在 `getAllConfig` 和 `getItemsFromMap` 中进行统一的过滤？

2022-06-24 11:58 UTC, hyj1991 commented on src/loader/impl/plugin_config.ts
> +          throw new Error(`Plugin ${pluginName} config can't have both package and path at ${item.path}`);
合并后本来就可能同时存在 `package` 和 `path` 属性的吧？这里应该按照 `package` 和 `path` 值来源的 env，确定是以 `package` 为准或者以  `path` 为准，而不是一定是 `package` 覆盖掉 `path` 的逻辑。

上次讨论的结果应该指的是确认使用 `package` or `path` 属性作为最终的插件路径来源后，为了方便 Scanner 的处理，我们在扫描器内部将这个最终确定的结果统一转换为 `path`

2022-06-24 12:01 UTC, hyj1991 requested changes
以上一些实现需要再确认下

2022-06-27 02:52 UTC, hyj1991 commented on src/scanner/scan.ts
> +      configList = configList.concat(this.tmpConfigStore.get(env) ?? []);
另外忘记说了，其实 concat 和 unshift 的性能都是比较差的，性能最佳的方式是 push 最后 reverse

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +    this.tmpConfigStore = new Map();
fixed.

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +  private itemMap: Map<string, ManifestItem[]> = new Map();
拆了一单独的 initItemMap 方法，属性初始化就有必要了；拆方法的原因时每个 env 都需要一个干净的 itemMap，否则会出现重复项，是个 BUG

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +    const root = path.resolve(baseDir, configDir);
对于 getAllConfig，对它扫描工作的根就是配置目录自身把，感觉还好？

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +      }
有关这个 PR 所解决的主要问题，package/path 的统一逻辑，在 PluginConfigLoader 里面，我是觉得扫描时和运行时统一逻辑，会省去后面很多问题，现在是因为 FrameworkConfigLoader 实现的比较粗，会有问题，所以临时加了判断

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +      configList = configList.concat(this.tmpConfigStore.get(env) ?? []);
TS 的 Map.get 会有个 `| undefined` 类型，加了也没啥副作用，总比 as 好

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +      configList = configList.concat(this.tmpConfigStore.get(env) ?? []);
性能问题后面再处理吧，concat 和 unshift 半斤八两

2022-06-27 03:38 UTC, noahziheng commented on src/scanner/scan.ts
> +    });
语法简化done

抽象的问题感觉有个悖论，仅 Scan 期间需要自然是因为有对应逻辑在 Scanner 里面，而 Scanner 参数是外面传的，把内部逻辑需要的过滤参数交给外面控制，就很怪

2022-06-27 03:41 UTC, noahziheng commented on src/loader/impl/plugin_config.ts
> +          throw new Error(`Plugin ${pluginName} config can't have both package and path at ${item.path}`);
这个位置处理是在合并前，刚读到单个文件的时候，单个文件对应的单个插件项肯定不能同时出现 package/path 吧

2022-06-27 03:42 UTC, noahziheng commented
@hyj1991 再看下

2022-06-27 06:11 UTC, hyj1991 commented on src/scanner/scan.ts
> +    const root = path.resolve(baseDir, configDir);
主要是 `root` 的概念在 Scanner 里更多指的是扫描基准单位的根路径

2022-06-27 06:13 UTC, hyj1991 commented on src/scanner/scan.ts
> +    });
> 把内部逻辑需要的过滤参数交给外面控制

内部属性也可以不被外部覆盖的写法，这样这个特殊的逻辑就是 Scanner 自己所需要的一个不被外部影响的属性决定了

2022-06-27 06:15 UTC, hyj1991 commented on src/scanner/scan.ts
> +  private itemMap: Map<string, ManifestItem[]> = new Map();
我的意思是既然构造器里执行了初始化，属性定义是不是不需要初始化？

```ts
private itemMap: Map<string, ManifestItem[]>;
```

2022-06-27 06:15 UTC, hyj1991 commented on src/scanner/scan.ts
> +  private itemMap: Map<string, ManifestItem[]> = new Map();
构造函数无论如何都会执行到

2022-06-27 06:16 UTC, hyj1991 commented on src/scanner/scan.ts
> +    const root = path.resolve(baseDir, configDir);
当然这个命名不是什么特别重要的问题。

2022-06-27 06:18 UTC, hyj1991 commented on src/scanner/scan.ts
> +      }
直接用 `config loader` 来处理 config，这样得到的就是：

```ts
{
  "plugin": { xxxxx }
}
```

后面只对 `allConfig.plugin` 处理是不是看起来更简洁一些。

2022-06-27 08:53 UTC, noahziheng commented on src/scanner/scan.ts
> +  private itemMap: Map<string, ManifestItem[]> = new Map();
1. initItemMap 已经不在构造函数里了，再看看
2. 它是异步方法，这里不放个 new 的话 TS 会有类型错误
 
![image](https://user-images.githubusercontent.com/2758317/175900032-90820254-6363-4ff6-a5ea-1cbb448b04cd.png)

2022-06-27 08:57 UTC, noahziheng commented on src/scanner/scan.ts
> +    });
感觉暂时没必要，后面类似 type 多了再说吧？

2022-06-27 09:00 UTC, hyj1991 approved these changes

2022-06-27 09:00 UTC, merged