WIP: refactor: app add loader hook
artusjs/core pull request #131
Opened 2022-07-11 12:47 UTC by JerrysShan

2022-07-12 03:34 UTC, noahziheng requested changes

2022-07-12 03:34 UTC, noahziheng commented on src/loader/factory.ts
> +  private loaderEvent: LoaderEventEmitter;
loaderEvent 这个命令好像不太妥，不达意

2022-07-12 03:34 UTC, noahziheng commented on src/loader/factory.ts
> +  addLoaderListener(eventName: string, listener: LoaderEventListener) {
对等的 `removeListener` 也要暴露出来吧

2022-07-12 03:34 UTC, noahziheng commented on src/loader/factory.ts
> +  private loaderEvent: LoaderEventEmitter;
考虑直接 loaderEmiiter 或者 loaderEventEmitter 清楚一些

2022-07-13 09:05 UTC, JerrysShan commented
这个改动主要是为了暴露自定义 loader hook 的API ， 满足上层框架自定义 loader hook 的需求

2022-07-13 09:54 UTC, hyj1991 requested changes

2022-07-13 09:54 UTC, hyj1991 commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
这里为啥还要加 `env`？，manifest 是已经明确了 env 后的结果了，不会再有非需要启动的 env 下配置传进来的场景

2022-07-18 11:28 UTC, JerrysShan commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
现在获取的是 ARTUS_ENV 环境变量，上层不会用这个，而是用自定义的

2022-07-18 12:21 UTC, noahziheng commented on src/loader/factory.ts
> +    await this.loadItemList(manifest.items, root);
感觉可以撤掉 loadItemList 了？

2022-07-18 12:57 UTC, hyj1991 commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
我的意思是，loadManifest 的时候，传入的 manifest 已经是只包含需要使用的 env 对应的文件列表了，启动期不应该会关注到 env 才对

2022-07-19 08:16 UTC, JerrysShan commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
启动阶段获取根据 env 获取配置的时候也用到了

2022-07-19 11:40 UTC, JerrysShan commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
我明白这个逻辑，但是获取合并后的配置还是需要 env 这个参数；如果不传递，就走了默认值 ARTUS_SERVER_ENV 了，我们不用这个环境变量
![image](https://user-images.githubusercontent.com/13977368/179741477-4ec44aef-38e1-490c-b402-7dbb5d730741.png)

2022-07-19 11:47 UTC, hyj1991 commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
那是否应该修改这里的逻辑，毕竟启动期并不需要 env

2022-07-19 12:27 UTC, JerrysShan commented on src/application.ts
> +    this.env = opts?.env ?? process.env[ARTUS_SERVER_ENV] ?? ARTUS_DEFAULT_CONFIG_ENV.DEV;
那感觉需要再暴露一个 getAllConfig 这样的 API，负责加载完 manifest 合并后的config 值

2022-07-25 12:38 UTC, noahziheng commented on src/loader/factory.ts
>    async loadItem(item: ManifestItem): Promise<void> {
`Promise<void>` 需要调整为 `Promise<any>`

2022-07-26 06:37 UTC, noahziheng approved these changes

2022-07-27 02:52 UTC, hyj1991 commented on src/configuration/index.ts
> +  }
这个合并会有问题吧？以 `configStore` 最后一个 env 为准了

2022-07-27 02:54 UTC, hyj1991 commented on src/loader/factory.ts
> +    return loader.load(item);
这里的改动目的是啥？

2022-07-27 02:56 UTC, hyj1991 commented
`style` 大量更改最好单独拆 pr，不要合并到 feature 的 pr 里，看起来有点乱

2022-07-27 02:58 UTC, hyj1991 commented on src/configuration/index.ts
> +  }
另外这里的 `getAllConfig` 是否可以和 Scanner 里面用到的 `getAllConfig` 实现合并？

2022-07-27 02:59 UTC, hyj1991 commented
`LoaderEventEmitter ` 自身的实现看起来并没有问题

2022-07-27 03:02 UTC, JerrysShan commented on src/configuration/index.ts
> +  }
启动后里面应该只有一个 env 和 default

2022-07-27 03:03 UTC, JerrysShan commented on src/loader/factory.ts
> +    return loader.load(item);
为了获取加载后的值，传递给 afterEach hook

2022-07-27 03:05 UTC, hyj1991 commented on src/loader/factory.ts
> +    return loader.load(item);
这样上面的 `async` 也可以去掉了，这个方法本身变成了同步，返回一个 promise 对象

2022-07-27 03:05 UTC, JerrysShan commented
> `style` 大量更改最好单独拆 pr，不要合并到 feature 的 pr 里，看起来有点乱

我看下，开发完运行了下 `lint:fix` ，貌似就有 format code 的更改了

2022-07-27 03:17 UTC, hyj1991 commented
> > `style` 大量更改最好单独拆 pr，不要合并到 feature 的 pr 里，看起来有点乱
> 
> 我看下，开发完运行了下 `lint:fix` ，貌似就有 format code 的更改了

这个 pr 就不用改了，下次可以分开提下

2022-07-27 03:32 UTC, hyj1991 approved these changes

2022-07-27 03:35 UTC, merged