feat: support inject in lifecycle
artusjs/core pull request #145
Opened 2022-07-15 07:01 UTC by hyj1991

ref: https://github.com/artusjs/core/issues/143

2022-07-27 07:20 UTC, JerrysShan commented
之前专门为 lifecycle 实现的装饰器貌似可以移除了

2022-07-27 08:38 UTC, hyj1991 commented
> 之前专门为 lifecycle 实现的装饰器貌似可以移除了

现在是存储 lifecycle 的 class 吧？看起来不能移除

2022-07-27 08:47 UTC, JerrysShan commented
> 现在是存储 lifecycle 的 class 吧？看起来不能移除

WithApplication , WithContainer 这几个好像是 lifecycyle 专用吧

2022-07-27 08:50 UTC, hyj1991 commented
对，这两个是可以去掉了，稍后我再改下

2022-08-01 06:24 UTC, JerrysShan commented
这个进度如何了，什么时候可以合并

2022-08-01 06:54 UTC, hyj1991 commented
cc @noahziheng @JerrysShan ，合并了 master，去除了 `WithXXX` 的 API 已经更新了对应的 test case

2022-08-01 07:11 UTC, JerrysShan approved these changes

2022-08-01 08:40 UTC, noahziheng requested changes
好像没有在 set 的时候用上 lazy？@hyj1991 @JerrysShan

2022-08-01 08:47 UTC, hyj1991 commented
我确认下 lazy set 如何实现的

2022-08-01 12:39 UTC, noahziheng approved these changes
LGTM

2022-08-01 12:39 UTC, JerrysShan approved these changes

2022-08-01 12:40 UTC, merged