Relative manifest
artusjs/core pull request #82
Opened 2022-05-23 23:55 UTC by hyj1991

2022-05-25 12:27 UTC, noahziheng requested changes

2022-05-25 12:27 UTC, noahziheng commented on src/application.ts
> +      manifest.items.forEach(item => item.path = path.join(root, item.path));
这个动作是不是可以放在 LoaderFactory.loadItem 里面做比较好，能少一次循环

2022-05-25 12:27 UTC, noahziheng commented on src/scanner/walk.ts
> +export default class Walk {
注意此处和 #81 的最新变化没同步，可能冲突

2022-05-25 12:56 UTC, hyj1991 commented on src/application.ts
> +      manifest.items.forEach(item => item.path = path.join(root, item.path));
此处已经修改

2022-05-26 01:35 UTC, hyj1991 commented
@noahziheng 有空看下，已经修改了

2022-05-26 01:39 UTC, noahziheng commented on src/loader/factory.ts
> +  async loadManifest(manifest: Manifest, root?: string): Promise<void> {
此处有 manifest 完整的对象，不用新增参数吧

2022-05-26 01:45 UTC, hyj1991 commented on src/loader/factory.ts
> +  async loadManifest(manifest: Manifest, root?: string): Promise<void> {
要么就是像之前的那样，在 `loadManifest` 调用之前把 `item.path` 拼接好

2022-05-26 04:57 UTC, noahziheng commented on src/loader/factory.ts
> +  async loadManifest(manifest: Manifest, root?: string): Promise<void> {
那我 get 了，先这样吧，透传了这么多级有点搞，后面再想想怎么调整下

2022-05-26 04:57 UTC, noahziheng approved these changes

2022-05-26 04:57 UTC, merged

2022-05-26 06:01 UTC, hyj1991 commented on src/loader/factory.ts
> +  async loadManifest(manifest: Manifest, root?: string): Promise<void> {
其实还有个办法，给 Manifest 再加一个 `root?: string` 属性，但是不是在 Scanner 阶段生成，而是启动期传入

2022-05-26 06:11 UTC, hyj1991 commented on src/loader/factory.ts
> +  async loadManifest(manifest: Manifest, root?: string): Promise<void> {
这样其实也只是少掉了一级传递 `load` -> `loadManifest`

而 `loadManifest` -> `loadItemList` 由于 `Manifest` 对象已经拆解为 `ManifestItem` 所以无论如何都要在循环前传递 `root` 属性过去